### ISSUE TITLE
credential support

### ISSUE THREAD

**Issue by tainewoo** [linniksa/redmine_git_mirror#12] opened 2019-05-14 07:13 UTC
such as:
ssh://xxxxxx@aaa.bbb.com:12345/ddd/eee.git
with ssh public key combined would be better.

**Comment by linniksa** [comment] 2019-05-14 08:09
duplicate of #6

**Closed as completed by linniksa** 2019-05-14 08:09 UTC

**Comment by gbonnefille** [comment] 2019-07-12 16:01
In my opinion, it is not exactly the same as #6 as the solution here is simpler. Here, we only need to let specify a user (not a password). And Git plainly support SSH with user, without any configuration or hack.

This pattern is required when the SSH port is relocated (for exemple, when running Gitlab in a Docker, mapping port to 2222). The URL is also: `ssh://git@gitlab.example.com:2222/group/project.git`.

The most anoying code is `has_credential?`: https://github.com/linniksa/redmine_git_mirror/blob/master/lib/redmine_git_mirror/url.rb#L86

I think the following code will do the job:
```ruby
def has_credential?
      return false if scp_like?

      return false if uses_ssh?  && password.to_s.empty?

      !password.to_s.empty? || !user.to_s.empty?
    end
```

**Comment by linniksa** [comment] 2019-07-13 08:21
ok, i agree, fix merged to master

**Comment by tainewoo** [comment] 2019-07-15 03:09
thank you all~~
